name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: apps/web/pnpm-lock.yaml

      - name: Install deps
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Test (CI)
        run: pnpm test:ci

      # optional: build to ensure prod build doesn’t fail
      - name: Build
        run: pnpm build
